FROM node:lts-buster
RUN git clone https://github.com/Rickydewizard/404-XMD/tree/patch-1.git
WORKDIR /root/404-XMD/tree/patch-1 
RUN npm install && npm install -g pm2 || yarn install --network-concurrency 1
COPY . .
EXPOSE 9090
CMD ["npm", "start"]


